name: release

on:
  push:
    branches: master                    # 2020年10月后github新建仓库默认分支改为main，注意更改
    tags: "*"

jobs:
  build:
    runs-on: ubuntu-22.04 # ubuntu-latest ubuntu的最新版本
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags') # 只在创建tags的时候才发布版本
    #if: github.event_name == 'push' || startsWith(github.ref, 'refs/tags') # 只在创建tags的时候才发布版本
    steps:
      - uses: actions/checkout@v4
      - name: 打印相关路径
        run: | # | 为 yaml 的特定符号，其下可以使用多行文字。
          echo "当前路径为 $(pwd)"
          ls -alh
          echo "github.workspace路径为 ${{ github.workspace }}"
          ls ${{ github.workspace }} -alh
          echo "HOME路径为 $HOME"
          ls $HOME -alh
      # 对于ubuntu22.04,编译4.19.71版本内核会有一些bug，需要对gcc进行降级
      - name: 运行 setup_env.sh 脚本设置环境
        run: |
          cd ${{ github.workspace }}
          ls -alh
          chmod 777 setup_env.sh
          ./setup_env.sh
          sudo apt install gcc-9
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100

      - name: 配置Git参数
        env:
          GITHUB_USER_NAME: ${{ secrets.GIT_USER_NAME }}
          GITHUB_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
        run: |
          git config user.name "$GITHUB_USER_NAME"
          git config user.email "$GITHUB_USER_EMAIL"

      - name: git拉取需要的仓库
        run: |
          cd ${{ github.workspace }}
          echo "⬇️ 下载所需要的仓库(只克隆最近一次提交记录)..."
          git clone --depth=2 https://gitee.com/sumumm/linux-shell-script.git
          git clone --depth=2 https://gitee.com/sumumm/linux-kernel.git
          git clone --depth=2 https://gitee.com/sumumm/linux-rootfs.git
          git clone --depth=2 https://gitee.com/sumumm/u-boot.git
          echo "✅ 下载完成,当前目录文件为:"
          ls -alh
          chmod 777 version.sh
          ./version.sh

      # - name: Cache ARM GCC
      #   id: cache-arm-linux-gnueabihf-gcc
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/2software
      #     key: ${{ runner.os }}-arm-linux-gnueabihf-gcc-8.3-2019.03

      - name: 安装交叉编译工具链
        if: steps.cache-arm-linux-gnueabihf-gcc.outputs.cache-hit != 'true'
        env:
          SHELL_ARG: ${{ secrets.SHELL_PARAM }}
        run: |
          cd ${{ github.workspace }}
          ls -alh
          cd linux-shell-script/develop
          chmod 777 arm-gcc.sh
          ./arm-gcc.sh $SHELL_ARG
          source ~/.bashrc
          source ~/.profile
          source ~/.bash_profile
          arm-linux-gnueabihf-gcc --version

      # - name: Setup tmate 
      #   uses: mxschmitt/action-tmate@v3

      - name: 编译uboot
        run: |
          cd ${{ github.workspace }}
          cd u-boot
          chmod 777 1.sh
          ./1.sh -p 1
      
      - name: 编译kernel
        run: |
          cd ${{ github.workspace }}
          cd linux-kernel
          chmod 777 build.sh
          ./build.sh -p 1
      
      - name: 制作打包根文件系统
        run: |
          cd ${{ github.workspace }}
          cd linux-rootfs
          chmod 777 1.sh
          ./1.sh -p 1

      # 会停在这里，我们用ssh调试,会有下面的打印
      # SSH: ssh HLZdjxXTgmyb8uk5rSRKujRfA@nyc1.tmate.io
      # or: ssh -i <path-to-private-SSH-key> HLZdjxXTgmyb8uk5rSRKujRfA@nyc1.tmate.io
      # 上传 rsync -avz <session_id>@tmate.io:/path/to/remote/file /path/to/local/directory
      # 同步 rsync -avz /path/to/local/file <session_id>@tmate.io:/path/to/remote/directory

      # - name: Setup tmate 
      #   uses: mxschmitt/action-tmate@v3

      - name: 打包所有成果物
        run: |
          cd ${{ github.workspace }}
          mkdir -p release
          cp -pvf ${{ github.workspace }}/u-boot/image_output/u-boot-*.tar.bz2 release
          cp -pvf ${{ github.workspace }}/kernel_nxp_4.19.71/image_output/kernel-*.tar.bz2 release
          cp -pvf ${{ github.workspace }}/linux-rootfs/buildroot-2023.05.1/output/images/rootfs-*.tar.bz2 release
          tar -jcf release.tar.bz2 release
          echo "✅ 打包完成，压缩包内文件为:"
          tar -tjf release.tar.bz2

      - name: 发布成果物
        id: new_release
        uses: softprops/action-gh-release@v2.0.8
        with:
          token: ${{ secrets.LINUX_RELEASE_PERSONAL_TOKEN }}
          tag_name: ${{ github.ref }}
          name: "Release ${{ github.ref }}"
          body: |
            **版本说明**  
            基于标签 ${{ github.ref }} 构建的稳定版本。
            更新内容详见 version.md。
          body_path: version.md  # 可选
          draft: false
          prerelease: false
          make_latest: true
          files: |
            README.md
            version.md
            release_uncompress.sh
            ${{ github.workspace }}/release.tar.bz2

            
