name: release

on:
  push:
    branches: master                    # 2020年10月后github新建仓库默认分支改为main，注意更改
    tags: "*"

jobs:
  build:
    runs-on: ubuntu-20.04 # ubuntu-latest ubuntu的最新版本
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags') # 只在创建tags的时候才发布版本
    #if: github.event_name == 'push' || startsWith(github.ref, 'refs/tags') # 只在创建tags的时候才发布版本
    steps:
      - uses: actions/checkout@v4
      - name: 打印相关路径
        run: | # | 为 yaml 的特定符号，其下可以使用多行文字。
          echo "当前路径为 $(pwd)"
          ls -alh
          echo "github.workspace路径为 ${{ github.workspace }}"
          ls ${{ github.workspace }} -alh
          echo "HOME路径为 $HOME"
          ls $HOME -alh
      
      - name: 运行 setup_env.sh 脚本设置环境
        run: |
          cd ${{ github.workspace }}
          ls -alh
          chmod 777 setup_env.sh
          ./setup_env.sh

      - name: 创建一个 readme.md 文件
        run: |
          echo "app_demo.out" > ${{ github.workspace }}/linux_app_demo/readme.md
          ls -alh

      - name: 配置Git参数
        env:
          GITHUB_USER_NAME: ${{ secrets.GIT_USER_NAME }}
          GITHUB_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
        run: |
          git config user.name "$GITHUB_USER_NAME"
          git config user.email "$GITHUB_USER_EMAIL"

      - name: git拉取需要的仓库
        run: |
          cd ${{ github.workspace }}
          git clone https://gitee.com/sumumm/linux-shell-script.git
          git clone https://gitee.com/sumumm/linux-kernel.git
          git clone https://gitee.com/sumumm/linux-rootfs.git
          ls -alh

      - name: 安装交叉编译工具链
        env:
          SHELL_ARG: ${{ secrets.SHELL_PARAM }}
        run: |
          cd ${{ github.workspace }}
          ls -alh
          cd linux-shell-script/develop
          chmod 777 arm-gcc.sh
          ./arm-gcc.sh $SHELL_ARG
          source ~/.bashrc
          source ~/.profile
          source ~/.bash_profile
          arm-linux-gnueabihf-gcc --version

      - name: 编译uboot
        run: |
          cd ${{ github.workspace }}
          git clone https://gitee.com/sumumm/u-boot.git
          cd u-boot
          chmod 777 1.sh
          ./1.sh -p 1
      
      - name: 编译kernel
        run: |
          cd ${{ github.workspace }}
          linux-kernel
          chmod 777 build.sh
          ./build.sh -p 1

      - name: 制作打包根文件系统
        run: |
          cd ${{ github.workspace }}
          cd linux-rootfs
          chmod 777 1.sh
          ./1.sh -g 1

      # 会停在这里，我们用ssh调试,会有下面的打印
      # SSH: ssh HLZdjxXTgmyb8uk5rSRKujRfA@nyc1.tmate.io
      # or: ssh -i <path-to-private-SSH-key> HLZdjxXTgmyb8uk5rSRKujRfA@nyc1.tmate.io
      # 上传 rsync -avz <session_id>@tmate.io:/path/to/remote/file /path/to/local/directory
      # 同步 rsync -avz /path/to/local/file <session_id>@tmate.io:/path/to/remote/directory

      # - name: Setup tmate 
      #   uses: mxschmitt/action-tmate@v3
      
      - name: 发布成果物
        id: new_release
        uses: softprops/action-gh-release@v2.0.8
        with:
          token: ${{ secrets.LINUX_RELEASE_PERSONAL_TOKEN }}
          name: release-latest
          make_latest: true
          files: |
            ${{ github.workspace }}/u-boot/image_output/u-boot-*.tar.bz2
            ${{ github.workspace }}/kernel_nxp_4.19.71/image_output/kernel-*.tar.bz2
            ${{ github.workspace }}/linux-rootfs/buildroot-2023.05.1/output/images/imx6ull_rootfs.tar.bz2
            
